-- 0006_media — L2.4 media pipeline schema (spec §4.3.7, §7).
--
-- One table for images, videos, and audio voice notes. R2 stores the
-- bytes, D1 stores the metadata. The Worker never proxies payload
-- bytes: clients PUT direct to R2 via a presigned URL, then commit
-- the row (§5.8, §7.3).
--
-- L2.4 scope (decisions.md D7–D11, 2026-04-20):
--   * Single-PUT path with a uniform 50 MiB raw cap across all kinds.
--   * Multipart (upload_id, parts, abort/resume) deferred to L2.4b.
--   * Client video transcode (ffmpeg.wasm) deferred to L2.4b.
--   * MP4 / Matroska GPS sidecar skipped; spec already treats it as
--     forensics backup — server trusts the request body.
--   * Derived renditions (thumbnails, video posters) deferred to L2.5+;
--     list endpoints return the original key for both url and
--     thumb_url until the derive consumer lands.
--
-- Time convention:
--   captured_at  INTEGER UTC epoch seconds (what the camera stamped)
--   received_at  INTEGER UTC epoch seconds (server's commit time)
--   deleted_at   INTEGER UTC epoch seconds (soft delete, §5.7)
-- Calendar date/time fields use TEXT elsewhere (§0001 header); media
-- timestamps are instants, not calendar dates, so they are epoch.
--
-- uuid: text ULID / UUIDv4 generated by the client before presign.
-- The same value is the R2 object key's terminal segment (§7.1:
-- `{kind}/{yyyy}/{mm}/{dd}/{village_id}/{uuid}.{ext}`) and will be
-- the outbox idempotency_key when L4 offline lands. Integer id stays
-- as the FK target for student.photo_media_id and
-- attendance_session.voice_note_media_id, matching the convention
-- for every other table.

PRAGMA foreign_keys = ON;

CREATE TABLE media (
  id INTEGER PRIMARY KEY,
  uuid TEXT NOT NULL UNIQUE,
  kind TEXT NOT NULL CHECK (kind IN ('image', 'video', 'audio')),
  r2_key TEXT NOT NULL UNIQUE,
  mime TEXT NOT NULL,
  bytes INTEGER NOT NULL CHECK (bytes > 0),
  captured_at INTEGER NOT NULL,
  received_at INTEGER NOT NULL,
  latitude REAL,
  longitude REAL,
  village_id INTEGER NOT NULL REFERENCES village(id),
  tag_event_id INTEGER REFERENCES event(id),
  created_by INTEGER NOT NULL REFERENCES user(id),
  deleted_at INTEGER,
  deleted_by INTEGER REFERENCES user(id)
);

CREATE INDEX idx_media_village_captured ON media(village_id, captured_at);
CREATE INDEX idx_media_event ON media(tag_event_id);
CREATE INDEX idx_media_kind_deleted ON media(kind, deleted_at);

-- Child photo (L2.1 deferred to L2.4; §3.2.2, §4.3.3).
ALTER TABLE student ADD COLUMN photo_media_id INTEGER REFERENCES media(id);

-- Attendance voice note (L2.2 deferred to L2.4; §3.3, §5.9).
ALTER TABLE attendance_session ADD COLUMN voice_note_media_id INTEGER REFERENCES media(id);
