#!/usr/bin/env node
// D36 step 5 — seed bridge for the Clerk + cookie-session hybrid.
//
// One-shot, dev-only. For every local seed user that does not yet
// carry a `clerk_user_id`, this script:
//
//   1. Looks up the user in Clerk by email. If found, captures the
//      Clerk ID. If not, creates a new Clerk user with a known dev
//      password (see CLERK_SEED_PASSWORD below).
//   2. Emits an UPDATE statement linking the local row to the Clerk
//      ID into a generated SQL file at db/seed-clerk-link.sql.
//   3. Applies that file against the local D1 via wrangler.
//
// Idempotent — running it twice is a no-op the second time. Existing
// Clerk users are reused (matched by email); existing links are
// skipped.
//
// Required env:
//   CLERK_SECRET_KEY      — sk_test_… from dashboard.clerk.com
// Optional env:
//   CLERK_SEED_PASSWORD   — default 'LabPassword2026!' (dev-only).
//                            Whatever value is used will be the
//                            login password for every seeded user.
//   DRY_RUN=1             — print actions, don't talk to Clerk or D1.
//
// Run (from repo root):
//   CLERK_SECRET_KEY=sk_test_… pnpm --filter @navsahyog/api seed:clerk
// Or directly:
//   cd apps/api && CLERK_SECRET_KEY=sk_test_… node scripts/seed-clerk.mjs

import { spawnSync } from 'node:child_process';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createClerkClient } from '@clerk/backend';

const __dirname = dirname(fileURLToPath(import.meta.url));
const apiDir = join(__dirname, '..');
const repoRoot = join(apiDir, '..', '..');
const linkSqlPath = join(repoRoot, 'db', 'seed-clerk-link.sql');

const SECRET = process.env.CLERK_SECRET_KEY;
const PASSWORD = process.env.CLERK_SEED_PASSWORD ?? 'LabPassword2026!';
const DRY_RUN = process.env.DRY_RUN === '1';

if (!SECRET && !DRY_RUN) {
  console.error('seed-clerk: CLERK_SECRET_KEY is required (or DRY_RUN=1)');
  process.exit(1);
}

// Pull the unlinked seed users from the local D1. wrangler's --json
// emits an array with one element per statement; each element has a
// `results` array of rows.
function fetchUnlinkedUsers() {
  if (DRY_RUN) {
    return [
      { id: 1, user_id: 'vc-anandpur', email: 'vc-anandpur@nsf.local', full_name: 'Sunita Patil' },
      { id: 6, user_id: 'super', email: 'super@nsf.local', full_name: 'Super Admin' },
    ];
  }
  const res = spawnSync(
    'pnpm',
    [
      'exec',
      'wrangler',
      'd1',
      'execute',
      'navsahyog_db',
      '--local',
      '--json',
      '--command',
      "SELECT id, user_id, email, full_name FROM user WHERE clerk_user_id IS NULL AND email IS NOT NULL",
    ],
    { cwd: apiDir, encoding: 'utf8' },
  );
  if (res.status !== 0) {
    console.error('seed-clerk: wrangler query failed');
    console.error(res.stderr);
    process.exit(1);
  }
  // wrangler emits a banner before the JSON; the JSON body itself
  // is the last `[{ … }]`-shaped chunk. Find it by scanning from
  // the first '[' character at the start of a line.
  const stdout = res.stdout;
  const start = stdout.indexOf('[\n');
  const json = start >= 0 ? stdout.slice(start) : stdout;
  const parsed = JSON.parse(json);
  return parsed[0]?.results ?? [];
}

async function ensureClerkUser(clerk, row) {
  const email = row.email;
  // Look up by email — if the admin (or a prior run) already created
  // the Clerk user, reuse it.
  const existing = await clerk.users.getUserList({
    emailAddress: [email],
    limit: 1,
  });
  if (existing.data.length > 0) {
    return { clerkUserId: existing.data[0].id, created: false };
  }
  // Create. Username matches the local user_id so the Clerk
  // dashboard is browsable by the same handle. Names are dummy data.
  const created = await clerk.users.createUser({
    emailAddress: [email],
    password: PASSWORD,
    username: row.user_id.replaceAll('-', '_'),
    firstName: row.full_name.split(' ')[0] ?? '',
    lastName: row.full_name.split(' ').slice(1).join(' '),
    skipPasswordChecks: true,
    skipPasswordRequirement: false,
  });
  return { clerkUserId: created.id, created: true };
}

function applyLinkSql(rows) {
  if (rows.length === 0) {
    console.log('seed-clerk: nothing to link.');
    return;
  }
  const lines = [
    '-- Generated by scripts/seed-clerk.mjs (D36 step 5).',
    '-- Re-runs are safe; the WHERE clause is keyed on email.',
    '',
    ...rows.map(
      (r) =>
        `UPDATE user SET clerk_user_id = '${r.clerkUserId.replaceAll(
          "'",
          "''",
        )}', clerk_synced_at = unixepoch() WHERE email = '${r.email.replaceAll(
          "'",
          "''",
        )}' AND clerk_user_id IS NULL;`,
    ),
    '',
  ];
  mkdirSync(dirname(linkSqlPath), { recursive: true });
  writeFileSync(linkSqlPath, lines.join('\n'));
  console.log(`seed-clerk: wrote ${linkSqlPath}`);

  if (DRY_RUN) {
    console.log('seed-clerk: DRY_RUN=1 — skipping wrangler apply.');
    return;
  }
  const res = spawnSync(
    'pnpm',
    [
      'exec',
      'wrangler',
      'd1',
      'execute',
      'navsahyog_db',
      '--local',
      '--file',
      linkSqlPath,
    ],
    { cwd: apiDir, stdio: 'inherit' },
  );
  if (res.status !== 0) {
    console.error('seed-clerk: wrangler apply failed');
    process.exit(1);
  }
}

async function main() {
  const users = fetchUnlinkedUsers();
  console.log(`seed-clerk: ${users.length} unlinked user(s) to bridge`);
  if (users.length === 0) return;

  const clerk = DRY_RUN ? null : createClerkClient({ secretKey: SECRET });

  const linked = [];
  for (const row of users) {
    if (DRY_RUN) {
      console.log(`  [dry] would ensure Clerk user for ${row.email}`);
      linked.push({ ...row, clerkUserId: 'user_dry_run_' + row.id });
      continue;
    }
    try {
      const { clerkUserId, created } = await ensureClerkUser(clerk, row);
      console.log(
        `  ${created ? 'created' : 'reused '} ${row.email.padEnd(36)} → ${clerkUserId}`,
      );
      linked.push({ ...row, clerkUserId });
    } catch (err) {
      console.error(`  failed   ${row.email}: ${err.message ?? err}`);
    }
  }

  applyLinkSql(linked);
  console.log('');
  console.log(`seed-clerk: ${linked.length} user(s) linked.`);
  console.log(`             dev sign-in password: ${PASSWORD}`);
  console.log('             (override via CLERK_SEED_PASSWORD env)');
}

main().catch((err) => {
  console.error('seed-clerk: unexpected error');
  console.error(err);
  process.exit(1);
});
